'use strict';

module.exports = [
  // Slider questions (1-30)
  { id: 1,  text: "How round is a circle? (0 = not round, 1 = perfectly round)", type: "slider", category: "clear" },
  { id: 2,  text: "How necessary is oxygen for human survival? (0 = unnecessary, 1 = absolutely essential)", type: "slider", category: "clear" },
  { id: 3,  text: "How hot is the surface of the sun? (0 = cold, 1 = extremely hot)", type: "slider", category: "clear" },
  { id: 4,  text: "How fast is light compared to sound? (0 = same speed, 1 = incomparably faster)", type: "slider", category: "clear" },
  { id: 5,  text: "How large is Jupiter compared to Earth? (0 = same size, 1 = vastly larger)", type: "slider", category: "clear" },
  { id: 6,  text: "How deep is the ocean compared to a bathtub? (0 = similar, 1 = incomparably deeper)", type: "slider", category: "clear" },
  { id: 7,  text: "How old is the universe? (0 = very young, 1 = extremely old)", type: "slider", category: "clear" },
  { id: 8,  text: "How complex is the human brain compared to a pocket calculator? (0 = similar, 1 = incomparably more complex)", type: "slider", category: "clear" },
  { id: 9,  text: "How cold is outer space? (0 = room temperature, 1 = extremely cold)", type: "slider", category: "clear" },
  { id: 10, text: "How loud is a jet engine compared to a whisper? (0 = similar volume, 1 = incomparably louder)", type: "slider", category: "clear" },
  { id: 11, text: "How important is money for happiness? (0 = irrelevant, 1 = everything)", type: "slider", category: "ambiguous" },
  { id: 12, text: "How dangerous is artificial intelligence to humanity? (0 = harmless, 1 = existential threat)", type: "slider", category: "ambiguous" },
  { id: 13, text: "How much does luck determine life outcomes? (0 = not at all, 1 = completely)", type: "slider", category: "ambiguous" },
  { id: 14, text: "How overrated is university education? (0 = underrated, 1 = extremely overrated)", type: "slider", category: "ambiguous" },
  { id: 15, text: "How ethical is eating meat? (0 = completely unethical, 1 = perfectly ethical)", type: "slider", category: "ambiguous" },
  { id: 16, text: "How beautiful is mathematics? (0 = not at all, 1 = the most beautiful thing)", type: "slider", category: "ambiguous" },
  { id: 17, text: "How creative can AI become? (0 = never truly creative, 1 = more creative than humans)", type: "slider", category: "ambiguous" },
  { id: 18, text: "How fair is capitalism? (0 = completely unfair, 1 = perfectly fair)", type: "slider", category: "ambiguous" },
  { id: 19, text: "How meaningful is human life on a cosmic scale? (0 = meaningless, 1 = profoundly meaningful)", type: "slider", category: "ambiguous" },
  { id: 20, text: "How free is human will? (0 = fully determined, 1 = completely free)", type: "slider", category: "ambiguous" },
  { id: 21, text: "How close are we to solving climate change? (0 = nowhere near, 1 = almost there)", type: "slider", category: "ambiguous" },
  { id: 22, text: "How much privacy should people sacrifice for security? (0 = none, 1 = all of it)", type: "slider", category: "ambiguous" },
  { id: 23, text: "Is 2 + 2 equal to 4? (0 = no, 1 = yes)", type: "slider", category: "degenerate" },
  { id: 24, text: "Does gravity pull objects toward the Earth? (0 = no, 1 = yes)", type: "slider", category: "degenerate" },
  { id: 25, text: "Is ice colder than boiling water? (0 = no, 1 = yes)", type: "slider", category: "degenerate" },
  { id: 26, text: "Can humans breathe underwater without equipment? (0 = yes, 1 = no)", type: "slider", category: "degenerate" },
  { id: 27, text: "Is the Earth round? (0 = no, 1 = yes)", type: "slider", category: "degenerate" },
  { id: 28, text: "Is one year longer than one day? (0 = no, 1 = yes)", type: "slider", category: "degenerate" },
  { id: 29, text: "Do humans need food to survive? (0 = no, 1 = yes)", type: "slider", category: "degenerate" },
  { id: 30, text: "Does the sun rise in the east? (0 = no, 1 = yes)", type: "slider", category: "degenerate" },

  // Select questions (31-85)
  { id: 31, text: "Pick a number.", type: "select", category: "number", options: ["1","2","3","4","5","6","7","8","9","10"] },
  { id: 32, text: "Pick a Fibonacci number.", type: "select", category: "number", options: ["1","2","3","5","8","13","21","34","55","89"] },
  { id: 33, text: "Pick a perfect square.", type: "select", category: "number", options: ["1","4","9","16","25","36","49","64","81","100"] },
  { id: 34, text: "Pick a prime number.", type: "select", category: "number", options: ["2","3","5","7","11","13","17","19","23","29","31","37"] },
  { id: 35, text: "Pick a multiple of ten.", type: "select", category: "number", options: ["10","20","30","40","50","60","70","80","90","100"] },
  { id: 36, text: "Pick a digit.", type: "select", category: "number", options: ["0","1","2","3","4","5","6","7","8","9"] },
  { id: 37, text: "Pick a number.", type: "select", category: "number", options: ["3","7","12","22","35","42","58","69","77","88","91","100"] },
  { id: 38, text: "Pick a probability.", type: "select", category: "number", options: ["0.01","0.05","0.10","0.25","0.33","0.50","0.67","0.75","0.90","0.95","0.99"] },
  { id: 39, text: "Pick a power of two.", type: "select", category: "number", options: ["1","2","4","8","16","32","64","128","256","512","1024"] },
  { id: 40, text: "Pick a number.", type: "select", category: "number", options: ["1","2","3","4","5","6","7","8","9","1000"] },
  { id: 41, text: "Pick a number.", type: "select", category: "number", options: ["-50","-20","-10","-5","-1","0","1","5","10","20","50"] },
  { id: 42, text: "Pick a repeating number.", type: "select", category: "number", options: ["11","22","33","44","55","66","77","88","99","111"] },
  { id: 43, text: "Pick a decimal.", type: "select", category: "number", options: ["0.0","0.1","0.2","0.3","0.4","0.5","0.6","0.7","0.8","0.9","1.0"] },
  { id: 44, text: "Pick a constant.", type: "select", category: "number", options: ["0","1","e (2.72)","pi (3.14)","phi (1.62)","sqrt2 (1.41)","ln2 (0.69)","42","infinity","-1"] },
  { id: 45, text: "Pick a percentage.", type: "select", category: "number", options: ["0%","10%","20%","30%","40%","50%","60%","70%","80%","90%","100%"] },
  { id: 46, text: "Pick the most significant year in history.", type: "select", category: "history", options: ["3000 BC","500 BC","1 AD","1066","1492","1776","1789","1945","1969","2000"] },
  { id: 47, text: "When will humans first land on Mars?", type: "select", category: "future", options: ["2028","2030","2035","2040","2050","2075","2100","2200","2500","Never"] },
  { id: 48, text: "Pick the best age to be.", type: "select", category: "lifestyle", options: ["5","10","16","18","21","25","30","40","50","65","80"] },
  { id: 49, text: "Pick the best time of day.", type: "select", category: "lifestyle", options: ["06:00","07:00","08:00","10:00","12:00","14:00","17:00","19:00","20:00","22:00","00:00"] },
  { id: 50, text: "Pick the best month.", type: "select", category: "lifestyle", options: ["January","February","March","April","May","June","July","August","September","October","November","December"] },
  { id: 51, text: "Pick the best day of the week.", type: "select", category: "lifestyle", options: ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"] },
  { id: 52, text: "Pick the decade with the best music.", type: "select", category: "culture", options: ["1920s","1930s","1940s","1950s","1960s","1970s","1980s","1990s","2000s","2010s","2020s"] },
  { id: 53, text: "How long should a perfect vacation last?", type: "select", category: "lifestyle", options: ["1 day","3 days","1 week","2 weeks","1 month","3 months","6 months","1 year","5 years","Forever"] },
  { id: 54, text: "When will we achieve AGI?", type: "select", category: "future", options: ["Already here","2026","2028","2030","2035","2040","2050","2075","2100","Never"] },
  { id: 55, text: "Which century had the greatest impact on humanity?", type: "select", category: "history", options: ["1st","5th","10th","15th","17th","18th","19th","20th","21st","22nd (predicted)"] },
  { id: 56, text: "Pick the most intelligent non-human animal.", type: "select", category: "nature", options: ["Ant","Goldfish","Chicken","Cat","Dog","Pig","Elephant","Crow","Dolphin","Chimpanzee"] },
  { id: 57, text: "Pick the most important chemical element.", type: "select", category: "science", options: ["Hydrogen","Helium","Carbon","Nitrogen","Oxygen","Iron","Gold","Silver","Uranium","Platinum"] },
  { id: 58, text: "Pick the most important invention in history.", type: "select", category: "history", options: ["Fire","Wheel","Writing","Printing press","Compass","Steam engine","Electricity","Antibiotics","Internet","Nuclear energy"] },
  { id: 59, text: "Pick the most powerful human emotion.", type: "select", category: "psychology", options: ["Joy","Sadness","Anger","Fear","Surprise","Disgust","Love","Hope","Curiosity","Peace"] },
  { id: 60, text: "If you could safely visit one, which would you pick?", type: "select", category: "space", options: ["Mercury","Venus","Mars","Jupiter","Saturn","Uranus","Neptune","Pluto","The Moon","The Sun"] },
  { id: 61, text: "Pick the best superpower.", type: "select", category: "fantasy", options: ["Flight","Invisibility","Teleportation","Time travel","Mind reading","Super strength","Immortality","Shapeshifting","Telekinesis","Healing others"] },
  { id: 62, text: "If you could eat only one food forever, which?", type: "select", category: "lifestyle", options: ["Rice","Bread","Potato","Pasta","Corn","Chicken","Beef","Fish","Eggs","Cheese"] },
  { id: 63, text: "Which sense is most important?", type: "select", category: "psychology", options: ["Smell","Taste","Touch","Hearing","Sight"] },
  { id: 64, text: "Pick the most interesting number.", type: "select", category: "number", options: ["Zero","One","Two","Three","Five","Seven","Ten","Twelve","Thirteen","Forty-two","Hundred","Infinity"] },
  { id: 65, text: "Pick the most important virtue.", type: "select", category: "philosophy", options: ["Courage","Wisdom","Justice","Temperance","Honesty","Compassion","Loyalty","Humility","Patience","Gratitude"] },
  { id: 66, text: "Pick the most universal human fear.", type: "select", category: "psychology", options: ["Heights","Darkness","Spiders","Snakes","Death","Loneliness","Failure","Deep water","Public speaking","The unknown"] },
  { id: 67, text: "Pick the most beautiful color.", type: "select", category: "aesthetics", options: ["Red","Orange","Yellow","Green","Teal","Blue","Indigo","Violet","Pink","Gold","Black","White"] },
  { id: 68, text: "Pick the most beautiful time of year.", type: "select", category: "aesthetics", options: ["Early spring","Late spring","Early summer","Midsummer","Late summer","Early autumn","Mid autumn","Late autumn","Early winter","Midwinter"] },
  { id: 69, text: "Pick the most beautiful-sounding instrument.", type: "select", category: "aesthetics", options: ["Piano","Guitar","Violin","Cello","Flute","Trumpet","Saxophone","Harp","Drums","Human voice"] },
  { id: 70, text: "Pick the most fundamental science.", type: "select", category: "science", options: ["Mathematics","Physics","Chemistry","Biology","Computer science","Astronomy","Neuroscience","Ecology","Psychology","Philosophy"] },
  { id: 71, text: "Pick the word that best describes life.", type: "select", category: "philosophy", options: ["Always","Never","Sometimes","Maybe","Definitely","Probably","Rarely","Often","Impossible","Unpredictable"] },
  { id: 72, text: "Pick what matters most.", type: "select", category: "philosophy", options: ["Freedom","Security","Love","Power","Knowledge","Peace","Wealth","Health","Truth","Beauty"] },
  { id: 73, text: "Pick the fundamental principle of the universe.", type: "select", category: "philosophy", options: ["Order","Chaos","Balance","Change","Stillness","Growth","Decay","Cycles","Entropy","Emergence"] },
  { id: 74, text: "Pick the most important concept.", type: "select", category: "philosophy", options: ["Past","Present","Future","Moment","Eternity","Memory","Dream","Now","Change","Permanence"] },
  { id: 75, text: "Pick the most powerful material.", type: "select", category: "science", options: ["Wood","Stone","Glass","Steel","Gold","Water","Air","Fire","Light","Diamond"] },
  { id: 76, text: "Pick the warmest color.", type: "select", category: "aesthetics", options: ["White","Light yellow","Yellow","Gold","Orange","Coral","Red","Crimson","Maroon","Brown","Dark brown","Black"] },
  { id: 77, text: "Pick the coldest color.", type: "select", category: "aesthetics", options: ["White","Ice blue","Light cyan","Cyan","Teal","Blue","Navy","Indigo","Dark purple","Charcoal","Black"] },
  { id: 78, text: "Pick the shade that best represents 'neutral'.", type: "select", category: "aesthetics", options: ["White","Ivory","Light gray","Silver","Gray","Slate","Dark gray","Charcoal","Near-black","Black"] },
  { id: 79, text: "Pick the color of trust.", type: "select", category: "aesthetics", options: ["Red","Orange","Yellow","Green","Teal","Blue","Indigo","Violet","White","Gold","Black","Gray"] },
  { id: 80, text: "Pick the color of danger.", type: "select", category: "aesthetics", options: ["White","Yellow","Gold","Orange","Coral","Red","Crimson","Maroon","Dark red","Black"] },
  { id: 81, text: "Pick the most calming color.", type: "select", category: "aesthetics", options: ["White","Lavender","Light blue","Sky blue","Mint","Sage","Seafoam","Teal","Periwinkle","Soft pink","Cream","Gray"] },
  { id: 82, text: "Pick the color that represents 'moderate'.", type: "select", category: "aesthetics", options: ["Pure red","Warm red","Orange-red","Orange","Amber","Neutral","Teal","Cool blue","Blue","Deep blue"] },
  { id: 83, text: "Pick the color of intelligence.", type: "select", category: "aesthetics", options: ["Red","Orange","Yellow","Green","Teal","Blue","Indigo","Violet","Silver","Gold","White","Black"] },
  { id: 84, text: "Pick the color of money.", type: "select", category: "aesthetics", options: ["White","Cream","Light green","Green","Dark green","Gold","Silver","Brown","Blue","Black"] },
  { id: 85, text: "Pick the color of the future.", type: "select", category: "aesthetics", options: ["White","Silver","Light blue","Cyan","Teal","Electric blue","Purple","Violet","Neon green","Chrome","Black"] },

  // Estimation questions (86-100) — 60s commit phase
  { id: 86,  text: "What percentage of Earth's surface is water?", type: "select", category: "estimation", options: ["10%","20%","30%","40%","50%","60%","71%","80%","85%","90%"] },
  { id: 87,  text: "What percentage of the human body is water?", type: "select", category: "estimation", options: ["10%","20%","30%","40%","50%","60%","70%","80%","90%","95%"] },
  { id: 88,  text: "What fraction of people are left-handed?", type: "select", category: "estimation", options: ["1%","3%","5%","8%","10%","15%","20%","25%","30%","50%"] },
  { id: 89,  text: "What percentage of the universe is dark matter and dark energy?", type: "select", category: "estimation", options: ["5%","15%","25%","35%","50%","65%","75%","85%","95%","99%"] },
  { id: 90,  text: "What fraction of species that ever existed are now extinct?", type: "select", category: "estimation", options: ["10%","25%","40%","50%","60%","75%","80%","90%","95%","99%"] },
  { id: 91,  text: "How many languages are spoken in the world today?", type: "select", category: "estimation", options: ["50","200","500","1000","2000","3000","5000","7000","10000","15000"] },
  { id: 92,  text: "What percentage of the world's population lives in cities?", type: "select", category: "estimation", options: ["10%","20%","30%","40%","50%","57%","65%","75%","85%","95%"] },
  { id: 93,  text: "How old is the oldest known living tree (in years)?", type: "select", category: "estimation", options: ["100","500","1000","2000","3000","4000","5000","8000","10000","50000"] },
  { id: 94,  text: "What fraction of the ocean floor has been mapped in detail?", type: "select", category: "estimation", options: ["1%","5%","10%","20%","25%","40%","50%","75%","90%","100%"] },
  { id: 95,  text: "How many humans have ever lived on Earth?", type: "select", category: "estimation", options: ["1B","5B","10B","20B","50B","80B","100B","117B","200B","500B"] },
  { id: 96,  text: "What percentage of adults worldwide can read?", type: "select", category: "estimation", options: ["30%","40%","50%","60%","70%","75%","80%","87%","93%","99%"] },
  { id: 97,  text: "How many stars are visible to the naked eye on a clear night?", type: "select", category: "estimation", options: ["100","500","1000","2500","5000","10000","25000","50000","100000","1M"] },
  { id: 98,  text: "What percentage of Earth's land surface is desert?", type: "select", category: "estimation", options: ["5%","10%","15%","20%","25%","33%","40%","50%","60%","75%"] },
  { id: 99,  text: "How deep is the deepest point in the ocean (meters)?", type: "select", category: "estimation", options: ["1000","2000","3000","5000","7000","9000","11000","15000","20000","50000"] },
  { id: 100, text: "What fraction of Earth's freshwater is in glaciers and ice caps?", type: "select", category: "estimation", options: ["5%","10%","20%","30%","40%","50%","60%","69%","80%","90%"] },
];
